version: '3.4'

services:
  gamestore.api:
    container_name: gamestoreapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://gamestoredb:27017"
    depends_on:
        - gamestore.db
    ports:
      - "8000:80"

  gamestore.client:
    container_name: gamestoreclient
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "GamestoreAPIUrl=http://gamestoreapi"
    depends_on:
        - gamestore.db
        - gamestore.api
    ports:
      - "8001:80"

  gamestore.db:
    container_name: gamestoredb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db