apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamestoreapi-deployment
  labels:
    app: gamestoreapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gamestoreapi
  template:
    metadata:
      labels:
        app: gamestoreapi
    spec:
      containers:
        - name: gamestoreapi
          image: gamestoreacr.azurecr.io/gamestoreapi:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: connection_string
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1m"
            limits:
              memory: "128Mi"
              cpu: "0.3"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: gamestoreapi-service
spec:
  type: NodePort
  selector:
    app: gamestoreapi
  ports:
    - protocol: TCP
      port: 80