apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamestoreclient-deployment
  labels:
    app: gamestoreclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gamestoreclient
  template:
    metadata:
      labels:
        app: gamestoreclient
    spec:
      containers:
        - name: gamestoreclient
          image: mlebowskit/gamestoreclient:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: GamestoreAPIUrl
              valueFrom:
                  configMapKeyRef:
                    name: gamestoreapi-configmap
                    key: gamestoreapi_url
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: gamestoreclient-service
spec:
  type: NodePort
  selector:
    app: gamestoreclient
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 80
      nodePort: 30000